server.port: 8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost.sqlserver.rds.aliyuncs.com:3433;Databasename=aslog
#    url: jdbc:sqlserver://rm-m5e3353jy02cidl21eo.sqlserver.rds.aliyuncs.com:3433;Databasename=aslog
    username: sasa
    password: Sa123456
#  jpa:
#    database: sql_server
#    hibernate:
#      ddl-auto: update
#      naming:
#        #数据表命名下划线问题
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLServer2008Dialect
  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.kj.crosstrade.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


