server.port: 8080
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost.sqlserver.rds.aliyuncs.com:3433;Databasename=aslog
    username: sasa
    password: Sa123456
  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  type-aliases-package: com.kj.crosstrade.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


